### ISSUE TITLE
HandholdJS

### ISSUE THREAD

**Issue by hougasian** [ritterim/handholdJS#2]
## 🚀 Feature Request

A configurable JS-based tutorial walkthrough that can ultimately be loaded via npm. 
Easily added and lightly themed.

## Who is asking for the feature?

@hougasian

**Comment by hougasian** [comment]
Such a great start @mrtrimble !!

<img width="255" alt="Screen Shot 2022-08-08 at 3 20 30 PM" src="https://user-images.githubusercontent.com/6231956/183498820-0d917499-06b2-4594-9151-661eee3fcadf.png">


https://user-images.githubusercontent.com/6231956/183499207-7fa5d6af-c581-4d8c-8bb8-3f85dd833dc9.mov


https://user-images.githubusercontent.com/6231956/183500357-d16cad5f-9af4-41b3-b669-6285b6e93fb2.mov

**Comment by hougasian** [comment]
moving to ice box for later consideration.

**Comment by mrtrimble** [comment]
Made more issues for Handhold, closing this one!
